stages:
  - docker
  - mtool

.reg-image: &reg-image
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: docker
  variables:
    VERSION: 2
    DOCKER_DRIVER: overlay2

manifest:
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: mtool
  variables:
    ARCH: amd64
    ARCHS: linux/amd64,linux/arm,linux/arm64
    MTOOL_VER: 0.7.0
    REPO: $CI_REGISTRY_IMAGE:2
  script:
    - apk add --no-cache curl
    - curl -sSL https://github.com/estesp/manifest-tool/releases/download/v${MTOOL_VER}/manifest-tool-linux-${ARCH} -o /usr/bin/manifest-tool
    - chmod +x /usr/bin/manifest-tool
    - echo $NOT_A_PASS | docker login -u $NOT_ME --password-stdin $CI_REGISTRY
    - manifest-tool push from-args --platforms $ARCHS --template $REPO-ARCH --target $REPO
    - docker logout

image arm:
  <<: *reg-image
  script:
    - export REG_ARCH=$(echo $CI_JOB_NAME | sed 's|image ||')
    - apk add --no-cache bash make
    - docker build --build-arg GOARCH=arm --build-arg GOARM=7 -t $CI_REGISTRY_IMAGE:$VERSION-$REG_ARCH .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
    - make push

image arm64:
  <<: *reg-image
  script:
    - export REG_ARCH=$(echo $CI_JOB_NAME | sed 's|image ||')
    - apk add --no-cache bash make
    - docker build --build-arg GOARCH=arm64 -t $CI_REGISTRY_IMAGE:$VERSION-$REG_ARCH .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
    - make push

image amd64:
  <<: *reg-image
  script:
    - export REG_ARCH=$(echo $CI_JOB_NAME | sed 's|image ||')
    - apk add --no-cache bash make
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION-$REG_ARCH .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
    - make push
